name: chat_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # because I'm lazy
  dash_chat: ^1.0.17

  socket_io_client: ^0.9.9
  multi_server_socket: ^1.0.2
  web_socket_channel: ^1.1.0
  flutter_socket_io: ^0.6.0
  flutter_socket_plugin: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

